# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de35b58999e6a7b95473935e016296cbb1a9b2a1199f9a96d237694a4102ce17f279681f1f5cbc651f5a53afa789e155e5538e990305680918ca5c279458b9b3

test:
  secret_key_base: 2293154210e65c1235904f490c9b7ebee364eca5d086fea9343f9f18077fb78baa6ac6e90f69d8b009f165aaf669025dfea1f1a37ae22c3298b36622d57b3880

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
